# Generated by Django 3.2.15 on 2022-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220906_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='weight_in_grams',
            new_name='measure',
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='measure_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
