# Generated by Django 3.2.15 on 2022-09-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220907_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='measure',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='measure_type',
            new_name='amount_type',
        ),
    ]
