# Generated by Django 3.2.15 on 2022-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount_type_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount_type_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
