# Generated by Django 3.2.15 on 2022-09-01 15:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=core.utils.image_filepath),
        ),
    ]
