# Generated by Django 3.2.15 on 2022-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_uk',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_desc_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_desc_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
